//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceOneDental.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_Lookup
    {
        public int Id { get; set; }
        public string Vendor { get; set; }
        public string SOD { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> UOM { get; set; }
        public string Brand { get; set; }
        public string VendorBrand { get; set; }
        public Nullable<short> OriginalSort { get; set; }
        public string RowId { get; set; }
        public System.DateTime Created { get; set; }
    }
}
